### ISSUE TITLE
Installing hermes-python from source

### ISSUE THREAD

**Issue by joanhofer** [snipsco/hermes-protocol#76]
I am trying to install hermes-python from source according to the instructions from:
https://pypi.org/project/hermes-python/

When running the following code using git bash: 
_mkdir -p platforms/hermes-python/target
CARGO_TARGET_DIR=platforms/hermes-python/target cargo rustc --lib --manifest-path hermes-mqtt-ffi/Cargo.toml --release -- --crate-type cdylib_

several files and folders are created in the folder "/hermes-protocol/platforms/hermes-python/target/release":
_build  deps  examples  hermes_mqtt_ffi.d  hermes_mqtt_ffi.dll  hermes_mqtt_ffi.dll.d  hermes_mqtt_ffi.dll.lib  hermes_mqtt_ffi.lib  incremental  libhermes_mqtt_ffi.d  libhermes_mqtt_ffi.rlib  native_

However the dynamically linked shared object library libhermes_mqtt_ffi.dylib is missing. 
Do you know what the reason could be?

**Comment by anthonyray** [comment]
I'm sorry, the documentation is a bit misleading on this subject and was written for `macOS`. 

Depending on the platform you are running these commands, the output varies in the extension it can either be : 
- ` libhermes_mqtt_ffi.dylib` (on MacOS)
- ` libhermes_mqtt_ffi.so` (on Linux)

You need to pick the correct extension platform. 
Stay tuned here, because I'll update the instructions to something that abstracts away this tedious copy step : http://hermespython.readthedocs.io/

Cheers.

**Comment by joanhofer** [comment]
Thank you for the reply. I'm using a Windows system. The dll file is called hermes_mqtt_ffi.dll. I will try to continue with this one.

**Comment by anthonyray** [comment]
Let us know how it went !

**Comment by anthonyray** [comment]
Closing this for now.
